#!/usr/bin/env python3
"""
Converts a built VS Code color theme into an Opus theme.

Usage: tools/port-vscode-theme.py <vscode-theme.json> <opus-theme-name>

Writes themes/<opus-theme-name>.json. A VS Code theme colors TextMate
scopes; Opus colors the capture names its highlight queries use
(Helix's). SYNTAX below says which TextMate scope each capture name
stands for, and the theme's own rules are then applied to that scope
the way VS Code would: the rule naming the longest dotted prefix wins.
A capture name whose scope no rule covers is left out, and falls back
to its own dotted parent at paint time.

Only the syntax colors come over: the editor's background and the rest
of the window keep following Adwaita.

The GitHub themes are generated by their repository's build
(`node src/index.js` writes themes/*.json) before this can read them.
"""
import json
import os
import re
import sys

# Opus capture name -> the TextMate scope a VS Code grammar gives the same thing.
SYNTAX = {
    "attribute": "entity.other.attribute-name",
    "comment": "comment",
    "constant": "constant",
    "constant.builtin": "constant.language",
    "constant.character.escape": "constant.character.escape",
    "constant.numeric": "constant.numeric",
    "constructor": "entity.name.type",
    "diff.delta": "markup.changed",
    "diff.minus": "markup.deleted",
    "diff.plus": "markup.inserted",
    "function": "entity.name.function",
    "function.builtin": "support.function",
    "function.macro": "entity.name.function.preprocessor",
    "keyword": "keyword",
    "keyword.operator": "keyword.operator",
    "keyword.storage": "storage",
    "keyword.storage.modifier": "storage.modifier",
    "keyword.storage.type": "storage.type",
    "label": "entity.name.label",
    "markup.bold": "markup.bold",
    "markup.heading": "markup.heading",
    "markup.italic": "markup.italic",
    "markup.link.label": "string.other.link",
    "markup.link.text": "string.other.link",
    "markup.link.url": "string.other.link",
    "markup.list": "punctuation.definition.list.begin.markdown",
    "markup.quote": "markup.quote",
    "markup.raw": "markup.inline.raw",
    "markup.strikethrough": "markup.strikethrough",
    "namespace": "entity.name.namespace",
    "operator": "keyword.operator",
    "string": "string",
    "string.regexp": "string.regexp",
    "string.special.url": "string.other.link",
    "tag": "entity.name.tag",
    "type": "entity.name.type",
    "type.builtin": "support.type",
    "type.enum.variant": "variable.other.enummember",
    "variable": "variable.other",
    "variable.builtin": "variable.language",
    "variable.other.member": "variable.other.property",
    "variable.parameter": "variable.parameter",
}

if len(sys.argv) != 3:
    sys.exit(f"usage: {sys.argv[0]} <vscode-theme.json> <opus-theme-name>")

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
with open(sys.argv[1]) as file:
    source = json.load(file)


def color(value):
    """#rgb and #rgba spelled out: Opus only reads the six- and eight-digit forms."""
    if re.fullmatch(r"#[0-9a-fA-F]{3,4}", value):
        value = "#" + "".join(digit * 2 for digit in value[1:])
    return value.lower()


def rules():
    """(scope, settings) for every rule naming a plain scope — one with no ancestor requirement."""
    for rule in source.get("tokenColors", []):
        scopes = rule.get("scope", [])
        if isinstance(scopes, str):
            scopes = scopes.split(",")
        for scope in scopes:
            scope = scope.strip()
            if scope and " " not in scope:
                yield scope, rule["settings"]


def settings_for(scope):
    best, best_length = None, -1
    for rule_scope, settings in rules():
        covers = scope == rule_scope or scope.startswith(rule_scope + ".")
        # `>=`: of two rules for the same scope, VS Code applies the later one.
        if covers and len(rule_scope) >= best_length:
            best, best_length = settings, len(rule_scope)
    return best


def style(settings):
    result = {}
    for key in ("foreground", "background"):
        if key in settings:
            result[key] = color(settings[key])
    for flag in settings.get("fontStyle", "").split():
        if flag in ("bold", "italic", "underline", "strikethrough"):
            result[flag] = True
    return result


syntax = {}
for key, scope in sorted(SYNTAX.items()):
    settings = settings_for(scope)
    if settings is not None and style(settings):
        syntax[key] = style(settings)

lines = ["{", '  "syntax": {']
lines.append(",\n".join(f"    {json.dumps(key)}: {json.dumps(value)}".replace('{"', '{ "').replace("}", " }") for key, value in syntax.items()))
lines += ["  }", "}"]

path = os.path.join(REPO_ROOT, "themes", sys.argv[2] + ".json")
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as file:
    file.write("\n".join(lines) + "\n")
print(os.path.relpath(path, REPO_ROOT))
