#!/usr/bin/env python3
"""
Regenerates every build file derived from the grammar pins in
languages/*/language.json, so a commit is only ever written there.

Usage: tools/sync-grammars.py

Run it after adding a bundled language or changing a "grammar" entry.
It writes:

  subprojects/<repository>.wrap                    fetches the pinned commit
  subprojects/packagefiles/<repository>/meson.build  exposes its C sources
  languages/meson.build                            compiles and installs them
  build/grammar-sources.json                       the same sources for
                                                   flatpak-builder, which
                                                   builds without network
"""
import configparser
import glob
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUBPROJECTS = os.path.join(REPO_ROOT, "subprojects")
PACKAGEFILES = os.path.join(SUBPROJECTS, "packagefiles")
LANGUAGES = os.path.join(REPO_ROOT, "languages")
GENERATED = "# Generated by tools/sync-grammars.py from languages/*/language.json — do not edit.\n"


def identifier(name):
    """A grammar name as a Meson variable and a C symbol suffix."""
    return re.sub(r"[-.]", "_", name)


def read_grammars():
    """repository name -> {"url", "rev", "grammars": [(name, path)]}, plus every package name."""
    repositories = {}
    packages = []
    for manifest_path in sorted(glob.glob(os.path.join(LANGUAGES, "*", "language.json"))):
        manifest = json.load(open(manifest_path))
        packages.append(os.path.basename(os.path.dirname(manifest_path)))
        grammar = manifest.get("grammar")
        if grammar is None:
            continue

        url = grammar["repository"]
        key = os.path.basename(url.rstrip("/")).removesuffix(".git")
        repository = repositories.setdefault(key, {"url": url, "rev": grammar["rev"], "grammars": []})
        if repository["rev"] != grammar["rev"]:
            sys.exit(f"{manifest_path}: {key} is pinned to two different commits")

        entry = (grammar.get("name", manifest["name"]), grammar.get("path", ""))
        if entry not in repository["grammars"]:
            repository["grammars"].append(entry)
    return repositories, packages


def write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as file:
        file.write(content)


def is_generated(path):
    with open(path) as file:
        return file.readline() == GENERATED


def remove_stale(repositories):
    """Drops what an earlier run generated for a grammar no package pins any more."""
    for wrap_path in glob.glob(os.path.join(SUBPROJECTS, "*.wrap")):
        key = os.path.basename(wrap_path).removesuffix(".wrap")
        if key in repositories or not is_generated(wrap_path):
            continue
        os.remove(wrap_path)
        overlay = os.path.join(PACKAGEFILES, key, "meson.build")
        if os.path.exists(overlay):
            os.remove(overlay)
            os.rmdir(os.path.dirname(overlay))


def wrap_file(key, repository):
    return (
        GENERATED
        + "[wrap-git]\n"
        + f"url = {repository['url']}\n"
        + f"revision = {repository['rev']}\n"
        + "depth = 1\n"
        + f"patch_directory = {key}\n"
    )


def overlay_file(key, repository):
    lines = [GENERATED, f"project('{key}', 'c')\n", "\nfs = import('fs')\n"]
    for name, path in repository["grammars"]:
        variable = identifier(name)
        src = f"{path}/src" if path else "src"
        lines += [
            f"\n{variable}_sources = files('{src}/parser.c')\n",
            f"{variable}_needs_cpp = false\n",
            f"if fs.exists('{src}/scanner.c')\n",
            f"  {variable}_sources += files('{src}/scanner.c')\n",
            f"elif fs.exists('{src}/scanner.cc')\n",
            f"  {variable}_sources += files('{src}/scanner.cc')\n",
            f"  {variable}_needs_cpp = true\n",
            "endif\n",
            f"{variable}_include = include_directories('{src}')\n",
        ]
    return "".join(lines)


def languages_meson(repositories, packages):
    lines = [
        GENERATED,
        "\n",
        "opus_grammars_install_dir = get_option('libdir') / 'opus' / 'grammars'\n",
        "opus_languages_install_dir = get_option('datadir') / 'opus' / 'languages'\n",
        "\n",
        "# Where an uninstalled build finds the grammars compiled below.\n",
        "opus_grammars_build_dir = meson.current_build_dir()\n",
        "opus_grammar_modules = []\n",
    ]
    for key, repository in sorted(repositories.items()):
        subproject = identifier(key)
        lines.append(f"\n{subproject} = subproject('{key}')\n")
        for name, _path in repository["grammars"]:
            variable = identifier(name)
            lines += [
                "# A compiler belongs to the project that builds with it, so the\n",
                "# one for a C++ scanner is added here, not in the subproject.\n",
                f"if {subproject}.get_variable('{variable}_needs_cpp')\n",
                "  add_languages('cpp', native: false)\n",
                "endif\n",
                "opus_grammar_modules += shared_module(\n",
                f"  '{name}',\n",
                f"  {subproject}.get_variable('{variable}_sources'),\n",
                f"  include_directories: {subproject}.get_variable('{variable}_include'),\n",
                "  # Generated parser tables and third-party scanners: not ours to fix.\n",
                "  c_args: ['-w'],\n",
                "  cpp_args: ['-w'],\n",
                "  name_prefix: '',\n",
                "  install: true,\n",
                "  install_dir: opus_grammars_install_dir,\n",
                ")\n",
            ]
    lines.append("\n")
    for package in packages:
        lines.append(f"install_subdir('{package}', install_dir: opus_languages_install_dir)\n")
    return "".join(lines)


def flatpak_sources():
    """Every wrap, hand-written ones included, as the sources flatpak-builder lays out where Meson expects a subproject."""
    sources = []
    for wrap_path in sorted(glob.glob(os.path.join(SUBPROJECTS, "*.wrap"))):
        key = os.path.basename(wrap_path).removesuffix(".wrap")
        wrap = configparser.ConfigParser()
        wrap.read(wrap_path)
        git = wrap["wrap-git"]
        revision = git["revision"]
        pin = "commit" if re.fullmatch(r"[0-9a-f]{40}", revision) else "tag"
        dest = f"subprojects/{key}"
        # No submodules: a grammar's own are test suites, never sources,
        # and one that has gone missing upstream would fail the build.
        sources.append({"type": "git", "url": git["url"], pin: revision, "dest": dest, "disable-submodules": True})

        overlay = os.path.join(PACKAGEFILES, git["patch_directory"])
        for root, _dirs, files in sorted(os.walk(overlay)):
            for name in sorted(files):
                relative_dir = os.path.relpath(root, overlay)
                sources.append({
                    "type": "file",
                    # Relative to the manifest's own directory, build/.
                    "path": os.path.relpath(os.path.join(root, name), os.path.join(REPO_ROOT, "build")),
                    "dest": os.path.normpath(os.path.join(dest, relative_dir)),
                })
    return json.dumps(sources, indent=2) + "\n"


repositories, packages = read_grammars()
remove_stale(repositories)
for key, repository in repositories.items():
    write(os.path.join(SUBPROJECTS, f"{key}.wrap"), wrap_file(key, repository))
    write(os.path.join(PACKAGEFILES, key, "meson.build"), overlay_file(key, repository))
    # Meson only lays the overlay over a subproject when it first
    # fetches it; one already on disk would keep the old build file.
    if os.path.isdir(os.path.join(SUBPROJECTS, key)):
        write(os.path.join(SUBPROJECTS, key, "meson.build"), overlay_file(key, repository))
write(os.path.join(LANGUAGES, "meson.build"), languages_meson(repositories, packages))
write(os.path.join(REPO_ROOT, "build", "grammar-sources.json"), flatpak_sources())
